#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Jun 25 16:13:58 IST 2025
# SW Build 5076996 on Wed May 22 18:36:09 MDT 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim downsampler_TB_behav -key {Behavioral:sim_1:Functional:downsampler_TB} -tclbatch downsampler_TB.tcl -view /home/mimos1/projects/practice_files/test_sampler/testbench_behav.wcfg -log simulate.log"
xsim downsampler_TB_behav -key {Behavioral:sim_1:Functional:downsampler_TB} -tclbatch downsampler_TB.tcl -view /home/mimos1/projects/practice_files/test_sampler/testbench_behav.wcfg -log simulate.log

